services:
  pihole:
    container_name: pihole
    image: ${PIHOLE_IMAGE}
    hostname: ${HOSTNAME}
    depends_on:
      unbound:
        condition: service_healthy
    environment:
      TZ: ${TIMEZONE}
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_dns_upstreams: 'unbound#5335'
      FTLCONF_dns_listeningMode: 'LOCAL'
      DNSMASQ_USER: root
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - ${PIHOLE_CONFIG_PATH}:/etc/pihole:rw
      - ${DNSMASQ_CONFIG_PATH}:/etc/dnsmasq.d:rw
    networks:
      lan_macvlan:
        ipv4_address: ${PIHOLE_MACVLAN_IP}
      dns_backend:
        ipv4_address: ${PIHOLE_BRIDGE_IP}
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: ${UNBOUND_IMAGE}
    hostname: unbound
    environment:
      TZ: ${TIMEZONE}
    networks:
      dns_backend:
        ipv4_address: ${UNBOUND_BRIDGE_IP}
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  lan_macvlan:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE}
    ipam:
      config:
        - subnet: ${MACVLAN_SUBNET}
          gateway: ${MACVLAN_GATEWAY}
  dns_backend:
    driver: bridge
    ipam:
      config:
        - subnet: ${BRIDGE_SUBNET}
          gateway: ${BRIDGE_GATEWAY}